name: Check mcon-tool

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install (Linux)
      run: |
        ./mcon-tool examples/E1.json -O tsv
        ./mcon-tool examples/E1.tsv
        ./mcon-tool examples/E1.tsv | ./mcon-tool -O tsv
        ./mcon-tool examples/E3.json -O tsv
        ./mcon-tool examples/E5.json -O tsv

        ./mcon-tool examples/E1.json --unnest
        ./mcon-tool examples/E1.json --atomize
        ./mcon-tool examples/E1.json --unnest --atomize
        ./mcon-tool examples/E1.json --unnest --atomize -O tsv
